spring:
  application:
    name: restaurant-api-gateway-zuul
server:
  port: 8080
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
zuul:
   routes:
      payment-management-service:
         path: /payment/**
         serviceId: payment
      user-management-service:
         path: /user/**
         serviceId: user-management-service
      order-management-service:
         path: /order/**
         url: http://localhost:8084/order