spring:
  application:
    name: restaurant-api-gateway-zuul
server:
  port: 8080
ribbon:
  eureka:
    enabled: true  
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
zuul:
   routes:
      user-management-service:
         path: /user/**
         serviceId: user-management-service